# The Site Configuration

# Use Chirpy theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: ar-SA

# Timezone
timezone: Asia/Riyadh

# Site info
title: Matrix blog
tagline: Windows Exploitation, Linux Exploitation , Red Teaming
description: >-
  Windows Exploitation, Linux Exploitation , Red Teaming

# Your site URL (no trailing slash!)
url: "https://matrix07ksa.github.io"

# Your GitHub username
github:
  username: Matrix07ksa

# Your Twitter username
twitter:
  username: Matrix0700

# Social info
social:
  name: Hejab Zairy Al-sharif
  email: hp515@protonmail.com
  links:
    - https://twitter.com/Matrix0700
    - https://github.com/Matrix07ksa

# Webmaster verification
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Analytics
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page views
pageviews:
  provider:

# Theme mode [light | dark]
theme_mode:

# CDN
cdn:

# Avatar on sidebar
avatar:

# Social preview image
social_preview_image:

# Global TOC switch
toc: true

# Comments system
comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

# Self-hosted static assets
assets:
  self_host:
    enabled:
    env:

# PWA settings
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

# Pagination
paginate: 10

# Baseurl (keep empty for user site)
baseurl: ""

# Plugins required by GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-archives

# Markdown settings
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections
collections:
  tabs:
    output: true
    sort_by: order

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# Sass
sass:
  style: compressed

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Exclude files
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

# Archives
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
